config/routes.rb
GrampianSpiderGroup::Application.routes.draw do
  

  
  resources :users do
    member do
    get :attending
    end
    member do
    get :records
    end
  end
  
  resources :events do
    member do
    get :attendees
    end
  end

  resources :sessions, :only => [:new, :create, :destroy]
  
  resources :registrations, :only => [:create, :destroy]
  
  resources :records 

  
  root                      :to => 'pages#home'
  
  match '/signup',          :to => 'users#new'
  
  match '/signin',          :to => 'sessions#new'
  
  match '/signout',         :to => 'sessions#destroy'

  match '/contact',         :to => 'pages#contact'
  
  match '/about',           :to => 'pages#about'
  
  match '/resources',       :to => 'pages#resources'
  
  match 'events',           :to => 'events#index'
  
  match  'events/show/:id', :to => 'events#show'
  
  match  'events/new',      :to => 'events#new'
  
  match 'records',           :to => 'records#index'
  
  match  'records/new',      :to => 'records#new'
  

end

app/views/shared/_attendeestats.html.erb
<div class="stats">
    <a href="<%= attendees_event_path(@event) %>">
      <span id="attendees" class="stat">
        <%= pluralize(@event.attendees.count, "attendee") %>
      </span>
    </a>
</div>

app/views/shared/_attendingstats.html.erb
<% @user = current_user %>
<div class="stats">
    <a href="<%= attending_user_path(@user) %>">
      <span id="attending" class="stat">
        <%= pluralize(@user.attending.count, "event") %> 
      </span>
    </a>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> 
        prohibited this <%= object.class.to_s.underscore.humanize.downcase %> 
        from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_recordstats.html.erb
<% @user = current_user %>
<div class="stats">
    <a href="<%= records_user_path(@user) %>">
      <span id="records" class="stat">
        <%= pluralize(@user.records.count, "record") %> 
      </span>
    </a>
</div>