config/routes.rb
GrampianSpiderGroup::Application.routes.draw do
  

  
  resources :users do
    member do
    get :attending
    end
    member do
    get :records
    end
  end
  
  resources :events do
    member do
    get :attendees
    end
  end

  resources :sessions, :only => [:new, :create, :destroy]
  
  resources :registrations, :only => [:create, :destroy]
  
  resources :records 

  
  root                      :to => 'pages#home'
  
  match '/signup',          :to => 'users#new'
  
  match '/signin',          :to => 'sessions#new'
  
  match '/signout',         :to => 'sessions#destroy'

  match '/contact',         :to => 'pages#contact'
  
  match '/about',           :to => 'pages#about'
  
  match '/resources',       :to => 'pages#resources'
  
  match 'events',           :to => 'events#index'
  
  match  'events/show/:id', :to => 'events#show'
  
  match  'events/new',      :to => 'events#new'
  
  match 'records',           :to => 'records#index'
  
  match  'records/new',      :to => 'records#new'
  

end

app/models/record.rb
class Record < ActiveRecord::Base
  attr_accessible  :date, :species, :location, :grid_ref, :comments, :latitude, :longitude
  
  acts_as_gmappable :process_geocoding => false
  
  belongs_to :user
  default_scope :order => 'records.created_at DESC'
  
  grid_regex = /^((([S]|[N])[A-HJ-Z])|(([T]|[O])[ABFGLMQRVW])|([H][L-Z])|([J][LMQRVW]))([0-9]{2})?([0-9]{2})?([0-9]{2})?([0-9]{2})?([0-9]{2})?$/
  
  validate  :future
  validates :user_id,   :presence => true
  validates :date,      :presence => true
  validates :location,  :presence => true,
                        :length   => { :maximum => 100 }
  validates :grid_ref,  :presence => true,
                        :length   => { :maximum => 100 },
                        :format   => { :with => grid_regex }
  validates :latitude,  :presence => true
  validates :longitude, :presence => true
  
  searchable do
    text :recorder, :species, :date_string, :location
  end
  
  def recorder
    user.name
  end
  
  def date_string
    date.strftime("%d %b %y")
  end
 
  def title
    "#{user.name} - #{species} - #{date.strftime("%d %b %y")} - #{location} - #{grid_ref}"
  end
  
  def future?
    date > Date.today
  end
  
  def future
    errors.add("date", "is in the future") if date && future?
  end

end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_filter :authenticate, :except => [:show, :create]
  before_filter :authorized_user, :only => [:edit, :update, :destroy]
  
  def index
    @search = Record.search do
      fulltext params[:search]
      paginate(:page => params[:page])
    end
    @records = @search.results
    @title = "All Records"
    @json = Record.all.to_gmaps4rails
  end
  
  def new
    @record = Record.new
    @title = "New Record"
  end
  
  def show
    @record = Record.find(params[:id])
    @title = @record.title
    @json = @record.to_gmaps4rails
  end
  
  def edit
    @record = Record.find(params[:id])
    @title = "Edit Record"
  end

  def create
    @record  = current_user.records.build(params[:record])
    
    respond_to do |format|
      if @record.save
        format.html { redirect_to(@record, :notice => 'Record was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end
  
  def update
    @record = Record.find(params[:id])
    
    if @record.update_attributes(params[:record])
      flash[:success] = "Record was successfully updated."
      redirect_to @record
    else
      @title = "Edit Record"
      render 'edit'
    end
  end

  def destroy
    Record.find(params[:id]).destroy
    flash[:success] = "Record was successfully removed."
    redirect_to records_path
  end
  
  private

    def authorized_user
      @record = current_user.records.find_by_id(params[:id])
      redirect_to root_path if @record.nil?
    end
  
end

app/views/records/_record.html.erb
<li>
  <%= link_to record.title, record %>
  
</li>

app/views/records/_record_form.html.erb
<%= form_for @record do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  
  <div class="field">
    <%= f.label :species %><br />
    <%= f.text_area :species, :rows => 1 %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_area :location, :rows => 1 %>
  </div>
  <div class="field">
    <%= f.label :grid_ref %><br />
    <%= f.text_area :grid_ref,  :rows => 1%>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_area :latitude,  :rows => 1%>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_area :longitude,  :rows => 1%>
  </div>
  <div class="field">
    <%= f.label :comments %><br />
    <%= f.text_area :comments, :rows => 6 %>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/records/edit.html.erb
<h1>Edit Record</h1>

<%= form_for(@record) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  
  <div class="field">
    <%= f.label :species %><br />
    <%= f.text_area :species, :rows => 1 %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_area :location, :rows => 1 %>
  </div>
  <div class="field">
    <%= f.label :grid_ref %><br />
    <%= f.text_area :grid_ref,  :rows => 1%>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_area :latitude,  :rows => 1%>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_area :longitude,  :rows => 1%>
  </div>
  <div class="field">
    <%= f.label :comments %><br />
    <%= f.text_area :comments, :rows => 6 %>
  </div>
    <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/records/index.html.erb
<p>
  <% if signed_in? %>
  <%= link_to 'Create a New Record', new_record_path %>
  <% end %>
<p>
  
<h1>All Records</h1>
<div class= "search"?
<%= form_tag events_path, :method => :get do %>
  <div id = "box", class="field">
    Search records:
    <%= text_field_tag :search, params[:search] %>
  </div>
  <div id= "button", class="actions">
    <%= submit_tag "Search" %>
  </div>
</div>
<% end %>

<div class= "map">
  <%= gmaps4rails(@json) %>
</div>

</br>
<%= will_paginate %>

<ul class="records">
  <%= render @records %>
</ul>
</br>

<%= will_paginate %>

app/views/records/new.html.erb
<h1>New record</h1>

<%= render 'record_form' %>

<%= link_to 'Back', records_path %>

app/views/records/show.html.erb
<h1>
  <b> Grampian Spider Group Record - <%= @record.id %></b>
</h1>

<div class= "map">
  <%= gmaps4rails(@json) %>
</div>

</br>

<p>
  <b>Species:</b>
  <%= @record.species %>
</p>

<p>
  <b>Date:</b>
  <%= @record.date.strftime("%d %b %y") %>
</p>

<p>
  <b>Location:</b>
  <%= @record.location %>
</p>

<p>
  <b>Grid Ref:</b>
  <%= @record.grid_ref %>
</p>

<p>
  <b>Latitude:</b>
  <%= @record.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @record.longitude %>
</p>

<p>
  <b>Comments:</b>
  <%= simple_format @record.comments %>
</p>

<p>
  <% if current_user?(@record.user) %>
  <%= link_to 'edit', edit_record_path(@record) %>
  | <%= link_to "delete", @record, :method => :delete, :confirm => "You sure?",
                                :title => "Delete record #{@record.id}"%>
  <% end %>
</p>

<p>
<%= link_to 'back', records_path %>
</p>