config/routes.rb
GrampianSpiderGroup::Application.routes.draw do
  

  
  resources :users do
    member do
    get :attending
    end
    member do
    get :records
    end
  end
  
  resources :events do
    member do
    get :attendees
    end
  end

  resources :sessions, :only => [:new, :create, :destroy]
  
  resources :registrations, :only => [:create, :destroy]
  
  resources :records 

  
  root                      :to => 'pages#home'
  
  match '/signup',          :to => 'users#new'
  
  match '/signin',          :to => 'sessions#new'
  
  match '/signout',         :to => 'sessions#destroy'

  match '/contact',         :to => 'pages#contact'
  
  match '/about',           :to => 'pages#about'
  
  match '/resources',       :to => 'pages#resources'
  
  match 'events',           :to => 'events#index'
  
  match  'events/show/:id', :to => 'events#show'
  
  match  'events/new',      :to => 'events#new'
  
  match 'records',           :to => 'records#index'
  
  match  'records/new',      :to => 'records#new'
  

end

app/models/event.rb
class Event < ActiveRecord::Base

  has_many    :reverse_registrations, :class_name => "Registration",
                                      :dependent => :destroy
  has_many    :attendees, :through => :reverse_registrations, :source => :user
  default_scope :order => 'events.date DESC'
  
  attr_accessible :date, :time, :location_name, :location_description, :grid_ref, :event_description, :latitude, :longitude
  
  acts_as_gmappable :process_geocoding => false
  
  grid_regex = /^((([S]|[N])[A-HJ-Z])|(([T]|[O])[ABFGLMQRVW])|([H][L-Z])|([J][LMQRVW]))([0-9]{2})?([0-9]{2})?([0-9]{2})?([0-9]{2})?([0-9]{2})?$/
  
  validate  :past
  validates :date,          :presence => true
  validates :time,          :presence => true
  validates :location_name, :presence => true,
                            :length   => { :maximum => 100 }
  validates :grid_ref,      :presence => true,
                            :length   => { :maximum => 14 },
                            :format   => { :with => grid_regex }
  validates :latitude,      :presence => true
  validates :longitude,     :presence => true
  
  searchable do
    text :location_name, :date_string
  end
  
  def date_string
    date.strftime("%d %b %y")
  end
  
  def title
    "#{location_name} - #{date.strftime("%d %b %y")}"
  end
  
  def past?
    date < Date.today
  end
  
  def past
    errors.add("date", "is in the past") if date && past?
  end
  

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate, :except => [:show, :create]
  before_filter :admin_user,   :only => [:new, :edit, :update, :destroy]
  
  def index
    @search = Event.search do
      fulltext params[:search]
      paginate(:page => params[:page])
    end
    @events = @search.results
    @title = "All Events"
    @json = Event.all.to_gmaps4rails
  end

  def new
    @event = Event.new
    @title = "New Event"
  end
  
  def show
    @event = Event.find(params[:id])
    @title = @event.location_name
    @json = @event.to_gmaps4rails
  end
  
  def edit
    @event = Event.find(params[:id])
    @title = "Edit Event"
  end
  
  def create
    @event = Event.new(params[:event])
    
    respond_to do |format|
      if @event.save
        format.html { redirect_to(@event, :notice => 'Event was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end
  
  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(params[:event])
      flash[:success] = "Event was successfully updated."
      redirect_to @event
    else
      @title = "Edit Event"
      render 'edit'
    end
  end
  
  def destroy
    Event.find(params[:id]).destroy
    flash[:success] = "Event was successfully removed."
    redirect_to events_path
  end
  
  def attendees
    @title = "Attendees"
    @event = Event.find(params[:id])
    @users = @event.attendees.paginate(:page => params[:page])
    render 'show_attendees'
  end
  
  private
  
  def authenticate
    deny_access unless signed_in?
  end
  
  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end
  
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_attend.html.erb
<%= form_for current_user.registrations.build(:event_id => @event.id),
              :remote => true do |f| %>
  <div><%= f.hidden_field :user_id %></div>
  <div class="actions"><%= f.submit "Attend" %></div>
<% end %>

app/views/events/_attend_form.html.erb
<div id="attend_form">
  <% if current_user.attending?(@event) %>
    <%= render 'unattend' %>
  <% else %>
    <%= render 'attend' %>
  <% end %>
</div>

app/views/events/_event.html.erb
<li>
  <%= link_to event.title, event %>
  
</li>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.time_select :time %>
  </div>
  <div class="field">
    <%= f.label :location_name %><br />
    <%= f.text_area :location_name, :rows => 1 %>
  </div>
  <div class="field">
    <%= f.label :location_description %><br />
    <%= f.text_area :location_description, :rows => 6 %>
  </div>
  <div class="field">
    <%= f.label :grid_ref %><br />
    <%= f.text_area :grid_ref,  :rows => 1%>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_area :latitude, :rows => 1 %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_area :longitude, :rows => 1 %>
  </div>
  <div class="field">
    <%= f.label :event_description %><br />
    <%= f.text_area :event_description, :rows => 6 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/_unattend.html.erb
<%= form_for current_user.registrations.find_by_event_id(@event),
             :html => { :method => :delete },
             :remote => true do |f| %>
  <div class="actions"><%= f.submit "Unattend" %></div>
<% end %>

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= form_for(@event) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.time_select :time %>
  </div>
  <div class="field">
    <%= f.label :location_name %><br />
    <%= f.text_area :location_name, :rows => 1 %>
  </div>
  <div class="field">
    <%= f.label :location_description %><br />
    <%= f.text_area :location_description, :rows => 6 %>
  </div>
  <div class="field">
    <%= f.label :grid_ref %><br />
    <%= f.text_area :grid_ref,  :rows => 1%>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_area :latitude, :rows => 1 %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_area :longitude, :rows => 1 %>
  </div>
  <div class="field">
    <%= f.label :event_description %><br />
    <%= f.text_area :event_description, :rows => 6 %>
  </div>
    <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p>
  <% if current_user.admin? %>
  <%= link_to 'Create a New Event', new_event_path(@event) %>
  <% end %>
<p>

<h1>All Events</h1>
<div class= "search"?
<%= form_tag events_path, :method => :get do %>
  <div id = "box", class="field">
    Search events:
    <%= text_field_tag :search, params[:search] %>
  </div>
  <div id= "button", class="actions">
    <%= submit_tag "Search" %>
  </div>
</div>
<% end %>

<div class= "map">
  <%= gmaps4rails(@json) %>
</div>

</br>
<%= will_paginate %>

<ul class="events">
  <%= render @events %>
</ul>
</br>

<%= will_paginate %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<h1>
  <%= @event.location_name %>
</h1>

<div class= "map">
  <%= gmaps4rails(@json) %>
</div>

</br>

<p>
  <%= render 'attend_form' if signed_in? %>
</p>

<p>
  <b>Date:</b>
  <%= @event.date.strftime("%d %b %y") %>
</p>

<p>
  <b>Time:</b>
  <%= @event.time.strftime("%H:%M") %>
</p>

<p>
  <b>Location Name:</b>
  <%= @event.location_name %>
</p>

<p>
  <b>Location Description:</b>
  <%= simple_format @event.location_description %>
</p>

<p>
  <b>Grid Ref:</b>
  <%= @event.grid_ref %>
</p>

<p>
  <b>Latitude:</b>
  <%= @event.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @event.longitude %>
</p>

<p>
  <b>Event Description:</b>
  <%= simple_format @event.event_description %>
</p>

<p>
  <%= render 'shared/attendeestats' %>
</p>

<p>
  
  <% if current_user.admin? %>
  <%= link_to 'edit', edit_event_path(@event) %>
  | <%= link_to "delete", @event, :method => :delete, :confirm => "You sure?",
                                :title => "Delete #{@event.location_name}"%>
  <% end %>
</p>

<p>
<%= link_to 'back', events_path %>
</p>

app/views/events/show_attendees.html.erb
<h1>All Attendees</h1>

<p>
  <%= @event.title %>
</p>

  <% unless @users.empty? %>
    <ul class="users">
      <%= render @users %>
    </ul>
    <%= will_paginate @users %>
  <% end %>