config/routes.rb
GrampianSpiderGroup::Application.routes.draw do
  

  
  resources :users do
    member do
    get :attending
    end
    member do
    get :records
    end
  end
  
  resources :events do
    member do
    get :attendees
    end
  end

  resources :sessions, :only => [:new, :create, :destroy]
  
  resources :registrations, :only => [:create, :destroy]
  
  resources :records 

  
  root                      :to => 'pages#home'
  
  match '/signup',          :to => 'users#new'
  
  match '/signin',          :to => 'sessions#new'
  
  match '/signout',         :to => 'sessions#destroy'

  match '/contact',         :to => 'pages#contact'
  
  match '/about',           :to => 'pages#about'
  
  match '/resources',       :to => 'pages#resources'
  
  match 'events',           :to => 'events#index'
  
  match  'events/show/:id', :to => 'events#show'
  
  match  'events/new',      :to => 'events#new'
  
  match 'records',           :to => 'records#index'
  
  match  'records/new',      :to => 'records#new'
  

end

app/views/layouts/_footer.html.erb
<div class="footer">
  <%= yield :scripts %>
</div> 
<div class= "language">
<p>
Languages: <%= link_to "English", url_for(:locale => 'en'), :class => "language" %>
| <%= link_to "Francais", url_for(:locale => 'fr'), :class => "language" %>
| <%= link_to "Espanol", url_for(:locale => 'es'), :class => "language" %>
</p>
</div>

app/views/layouts/_header.html.erb
    <div class="header"></div>
    <div class="logo">
      <ul>
        <li><%= link_to "Home", root_path %></li>
        
        <% if signed_in? %>
        <li><%= link_to t('header.Users'), users_path %></li>
        <li><%= link_to t('header.Profile'), current_user %></li>
        <li><%= link_to t('header.Settings'), edit_user_path(current_user) %></li>
        <% end %>
        <% if signed_in? %>
        <li><%= link_to t('header.Sign out'), signout_path, :method => :delete %></li>
        <% else %>
        <li><%= link_to t('header.Sign in'), signin_path %></li>
        <% end %>
      </ul>
    <%= image_tag("logo.jpg") %>
    </div>

app/views/layouts/_navigation.html.erb
    <div class="nav">
      <ul>
        <li><%= link_to t('navigation.About'), about_path %></li>
        <li><%= link_to t('navigation.Events'), events_path %></li>
        <li><%= link_to t('navigation.Records'), records_path %></li>
        <li><%= link_to t('navigation.Resources'), resources_path %></li>
        <li><%= link_to t('navigation.Contact'), contact_path %></li>
      </ul>
    </div>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag "style", :media => "all" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  
  <head>
    
    <title><%= title %></title>
    <%= render 'layouts/stylesheets' %>
    <%= csrf_meta_tag %>
    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag "gmaps4rails" %>
  </head>
  
  <body>
    
    <div class="container">
    <%= render 'layouts/header' %>
    <%= render 'layouts/navigation' %>
    <div class="content">
      <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    <%= render 'layouts/footer' %>
    </div>

  </body>
  
</html>